"""initial

Revision ID: ab2a1686883d
Revises: 
Create Date: 2025-04-02 17:32:26.096575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab2a1686883d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('internet_representation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vk', sa.String(), nullable=True),
    sa.Column('telegram', sa.String(), nullable=True),
    sa.Column('whatsapp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('representatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(), nullable=False, comment='Должность сотрудника, отвечающего за взаимодействие с Союзом'),
    sa.Column('full_name', sa.String(), nullable=False, comment='Фамилия, имя и отчество отвечающего за взаимодействие с Союзом'),
    sa.Column('email', sa.String(), nullable=False, comment='Е-мейл отвечающего за взаимодействие с Союзом'),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('power_of_attorney_number', sa.String(), nullable=True, comment='Номер доверенности (если есть) для сотрудника, отвечающего за взаимодействие с Союзом'),
    sa.Column('power_of_attorney_date', sa.Date(), nullable=True, comment='Дата выдачи доверенности для сотрудника, отвечающего за взаимодействие с Союзом'),
    sa.Column('power_of_attorney_place', sa.String(), nullable=True, comment='Место выдачи доверенности для сотрудника, отвечающего за взаимодействие с Союзом'),
    sa.Column('power_of_attorney_validity', sa.Date(), nullable=True, comment='Срок действия доверенности для сотрудника, отвечающего за взаимодействие с Союзом'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False, comment='Ваши фамилия, имя и отчество'),
    sa.Column('status', sa.Enum('individual', 'legal_entity', 'individual_entrepreneur', name='status'), nullable=False, comment='В каком статусе вы планируете участвовать в деятельности Союза?'),
    sa.Column('membership_level', sa.Enum('third_college_member', name='membershiplevel'), nullable=False, comment='Какой уровень участия в Союзе членства выбираете?'),
    sa.Column('passport_data', sa.String(), nullable=False, comment='Паспортные данные (серия, номер, дата выдачи, выдавший орган)'),
    sa.Column('address_data', sa.String(), nullable=False, comment='Адрес по прописке с индексом'),
    sa.Column('ogrnip', sa.Integer(), nullable=False, comment='Основной государственный регистрационный номер (ОГРНИП)'),
    sa.Column('organization_full_name', sa.String(), nullable=False, comment='Полное название организации'),
    sa.Column('organization_short_name', sa.String(), nullable=False, comment='Сокращенное название организации'),
    sa.Column('organizations_inn', sa.Integer(), nullable=False, comment='ИНН организации'),
    sa.Column('kpp', sa.Integer(), nullable=False, comment='КПП'),
    sa.Column('registration_in_tax_authority_date', sa.Date(), nullable=False, comment='Дата постановки на учет в налоговом органе'),
    sa.Column('organization_ogrn', sa.Integer(), nullable=False, comment='ОГРН организации'),
    sa.Column('organization_registration_date', sa.Date(), nullable=False, comment='Дата регистрации организации / ИП'),
    sa.Column('head_of_organization_position', sa.String(), nullable=False, comment='Должность руководителя организации'),
    sa.Column('head_of_organization_full_name', sa.String(), nullable=False, comment='Фамилия, имя, отчество руководителя организации'),
    sa.Column('position', sa.String(), nullable=False, comment='Ваша должность'),
    sa.Column('organization_main_okved_codes', sa.String(), nullable=False, comment='Укажите основной вид деятельности из выписки ЕГРИП (отдельный блок "Сведения об основном виде деятельности")'),
    sa.Column('occupation', sa.String(), nullable=False, comment='Чем в организации занимаетесь  лично вы'),
    sa.Column('legal_address_of_organization', sa.String(), nullable=False, comment='Адрес организации юридический'),
    sa.Column('main_business_place_address', sa.String(), nullable=False, comment='Адрес места основной деятельности организации'),
    sa.Column('mailing_address_with_zip_code', sa.String(), nullable=False, comment='Адрес для почтовой корреспонденции с индексом'),
    sa.Column('organizations_first_phone', sa.String(), nullable=False, comment='Телефон 1 организации / ИП'),
    sa.Column('organizations_second_phone', sa.String(), nullable=True, comment='Телефон 2 организации / ИП'),
    sa.Column('personal_phone', sa.String(), nullable=False, comment='Телефон личный в формате +7ХХХХХХХХХХ'),
    sa.Column('site', sa.String(), nullable=True, comment='Адрес сайта'),
    sa.Column('email', sa.String(), nullable=False, comment='Е-мейл организации / ИП'),
    sa.Column('representation_documents', sa.Enum('charter', 'power_of_attorney', name='representationvalidationdocuments'), nullable=False, comment='Документы, наделяющие вас правом представлять организацию в Союзе автосервисов'),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('current_account', sa.BigInteger(), nullable=False, comment='Расчетный счет'),
    sa.Column('correspondent_account', sa.BigInteger(), nullable=False, comment='Корреспондентский счет'),
    sa.Column('bic', sa.String(), nullable=False, comment='BIC'),
    sa.Column('towns', sa.ARRAY(sa.String()), nullable=False, comment='В каких городах и населенных пунктах работает ваше предприятие'),
    sa.Column('average_number_of_employees', sa.Integer(), nullable=False, comment='Среднесписочная численность организации'),
    sa.Column('number_of_services_and_repair_posts', sa.String(), nullable=False, comment='Количество сервисов и ремонтных  постов в каждом из них'),
    sa.Column('facade_photos', sa.ARRAY(sa.String()), nullable=False, comment='Приложите фотографии фасадов, клиентской зоны (если есть), общий вид рабочей зоны.'),
    sa.Column('side_services', sa.ARRAY(sa.Enum('spare_parts_store', 'cafe', 'car_wash_service', 'another', name='sideservices')), nullable=False, comment='Имеете ли при сервисе, даже если это не ваш бизнес'),
    sa.Column('organizations_specialization', sa.String(), nullable=False, comment='Какова специализация вашей организации?'),
    sa.Column('interaction', sa.Enum('in_person', 'representative', name='interaction'), nullable=False, comment='Как будете взаимодействовать с Союзом'),
    sa.Column('representative_id', sa.Integer(), nullable=True),
    sa.Column('internet_representation_id', sa.Integer(), nullable=True),
    sa.Column('interested_services', sa.ARRAY(sa.Enum('legal', 'information_support', 'property_valuation', 'staff_training', 'recruitment', 'tenders_support', 'electronic_trades_support', 'research', 'patent_science', 'exhibitions_participation', 'business_education', 'register_of_reliable_partners', 'other', name='interestedservices')), nullable=False, comment='В каких услугах Вы заинтересованы:'),
    sa.Column('can_be_useful', sa.String(), nullable=True, comment='Чем можете быть полезны (какую работу вести в Союзе, например, взаимодействие с органами власти, обучение персонала)?'),
    sa.Column('recommended_partner', sa.String(), nullable=True, comment='Кого бы Вы рекомендовали в качестве добросовестного партнера для сотрудничества  с Союзом автосервисов'),
    sa.Column('date_of_registration', sa.Date(), nullable=False, comment='Дата заполнения регистрационной формы'),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.ForeignKeyConstraint(['internet_representation_id'], ['internet_representation.id'], ),
    sa.ForeignKeyConstraint(['representative_id'], ['representatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    op.drop_table('representatives')
    op.drop_table('internet_representation')
    op.drop_table('banks')
    # ### end Alembic commands ###
